provider "oci" {}

resource "oci_core_instance" "generated_oci_core_instance" {
	agent_config {
		is_management_disabled = "false"
		is_monitoring_disabled = "false"
		plugins_config {
			desired_state = "DISABLED"
			name = "Vulnerability Scanning"
		}
		plugins_config {
			desired_state = "DISABLED"
			name = "Management Agent"
		}
		plugins_config {
			desired_state = "ENABLED"
			name = "Custom Logs Monitoring"
		}
		plugins_config {
			desired_state = "ENABLED"
			name = "Compute Instance Run Command"
		}
		plugins_config {
			desired_state = "ENABLED"
			name = "Compute Instance Monitoring"
		}
		plugins_config {
			desired_state = "DISABLED"
			name = "Block Volume Management"
		}
		plugins_config {
			desired_state = "DISABLED"
			name = "Bastion"
		}
	}
	availability_config {
		recovery_action = "RESTORE_INSTANCE"
	}
	availability_domain = "ocEU:US-ASHBURN-AD-3"
	compartment_id = "ocid1.compartment.oc1..aaaaaaaaj5nvdop25trab24p3mjjy3r6e5ujvp7742sku4tsha6j7wq6ftna"
	create_vnic_details {
		assign_private_dns_record = "true"
		assign_public_ip = "true"
		subnet_id = "ocid1.subnet.oc1.iad.aaaaaaaaozd4poqufajp7dgqnns3yy6lhtoxaiag2y56r2buplwkirs2ryxq"
	}
	display_name = "instance-20211008-2234"
	instance_options {
		are_legacy_imds_endpoints_disabled = "true"
	}
	is_pv_encryption_in_transit_enabled = "true"
	metadata = {
		"user_data" = "cnVuY21kOgogIAogLSB5dW0gaW5zdGFsbCAteSByc3lzbG9nIAoKCgogLSBmaXJld2FsbC1jbWQgLS1hZGQtcG9ydD01MTQvdGNwIC0tcGVybWFuZW50CgogLSBmaXJld2FsbC1jbWQgLS1hZGQtcG9ydD01MTQvdGNwIAoKIC0gZmlyZXdhbGwtY21kIC0tYWRkLXBvcnQ9NTE0L3VkcCAtLXBlcm1hbmVudAoKIC0gZmlyZXdhbGwtY21kIC0tYWRkLXBvcnQ9NTE0L3VkcAoKIAogLSBta2RpciAvdmFyL2xvZy9kZXBsb3ltZW50CiAtIHRvdWNoIC92YXIvbG9nL09DSS9kZXBsb3ltZW50LmxvZwogLSBlY2hvICRIT1NUTkFNRSA+PiAvdmFyL2xvZy9PQ0kvZGVwbG95bWVudC5sb2cgCiAtIGVjaG8gIiMgcnN5c2xvZyBjb25maWd1cmF0aW9uIGZpbGUKCiMgRm9yIG1vcmUgaW5mb3JtYXRpb24gc2VlIC91c3Ivc2hhcmUvZG9jL3JzeXNsb2ctKi9yc3lzbG9nX2NvbmYuaHRtbAojIG9yIGxhdGVzdCB2ZXJzaW9uIG9ubGluZSBhdCBodHRwOi8vd3d3LnJzeXNsb2cuY29tL2RvYy9yc3lzbG9nX2NvbmYuaHRtbCAKIyBJZiB5b3UgZXhwZXJpZW5jZSBwcm9ibGVtcywgc2VlIGh0dHA6Ly93d3cucnN5c2xvZy5jb20vZG9jL3Ryb3VibGVzaG9vdC5odG1sCgojIyMjIE1PRFVMRVMgIyMjIwoKbW9kdWxlKGxvYWQ9ImltdXhzb2NrIiAgICAjIHByb3ZpZGVzIHN1cHBvcnQgZm9yIGxvY2FsIHN5c3RlbSBsb2dnaW5nIChlLmcuIHZpYSBsb2dnZXIgY29tbWFuZCkKICAgICAgIFN5c1NvY2suVXNlPSJvbiIpICMgVHVybiBvZmYgbWVzc2FnZSByZWNlcHRpb24gdmlhIGxvY2FsIGxvZyBzb2NrZXQ7IAogICAgICAgICAgICAgICAgICAgICAgICAgICMgbG9jYWwgbWVzc2FnZXMgYXJlIHJldHJpZXZlZCB0aHJvdWdoIGltam91cm5hbCBub3cuCm1vZHVsZShsb2FkPSJpbWpvdXJuYWwiICAgICAgICAgICAgICMgcHJvdmlkZXMgYWNjZXNzIHRvIHRoZSBzeXN0ZW1kIGpvdXJuYWwKICAgICAgIFN0YXRlRmlsZT0iaW1qb3VybmFsLnN0YXRlIikgIyBGaWxlIHRvIHN0b3JlIHRoZSBwb3NpdGlvbiBpbiB0aGUgam91cm5hbAojbW9kdWxlKGxvYWQ9Imlta2xvZyIpICMgcmVhZHMga2VybmVsIG1lc3NhZ2VzICh0aGUgc2FtZSBhcmUgcmVhZCBmcm9tIGpvdXJuYWxkKQojbW9kdWxlKGxvYWQ9ImltbWFyayIpICMgcHJvdmlkZXMgLS1NQVJLLS0gbWVzc2FnZSBjYXBhYmlsaXR5CgojIFByb3ZpZGVzIFVEUCBzeXNsb2cgcmVjZXB0aW9uCiMgZm9yIHBhcmFtZXRlcnMgc2VlIGh0dHA6Ly93d3cucnN5c2xvZy5jb20vZG9jL2ltdWRwLmh0bWwKbW9kdWxlKGxvYWQ9ImltdWRwIikgIyBuZWVkcyB0byBiZSBkb25lIGp1c3Qgb25jZQppbnB1dCh0eXBlPSJpbXVkcCIgcG9ydD0iNTE0IikKCiMgUHJvdmlkZXMgVENQIHN5c2xvZyByZWNlcHRpb24KIyBmb3IgcGFyYW1ldGVycyBzZWUgaHR0cDovL3d3dy5yc3lzbG9nLmNvbS9kb2MvaW10Y3AuaHRtbAptb2R1bGUobG9hZD0iaW10Y3AiKSAjIG5lZWRzIHRvIGJlIGRvbmUganVzdCBvbmNlCmlucHV0KHR5cGU9ImltdGNwIiBwb3J0PSI1MTQiKQoKIyMjIyBHTE9CQUwgRElSRUNUSVZFUyAjIyMjCgojIFdoZXJlIHRvIHBsYWNlIGF1eGlsaWFyeSBmaWxlcwpnbG9iYWwod29ya0RpcmVjdG9yeT0iL3Zhci9saWIvcnN5c2xvZyIpCgojIFVzZSBkZWZhdWx0IHRpbWVzdGFtcCBmb3JtYXQKbW9kdWxlKGxvYWQ9ImJ1aWx0aW46b21maWxlIiBUZW1wbGF0ZT0iUlNZU0xPR19UcmFkaXRpb25hbEZpbGVGb3JtYXQiKQoKIyBJbmNsdWRlIGFsbCBjb25maWcgZmlsZXMgaW4gL2V0Yy9yc3lzbG9nLmQvCmluY2x1ZGUoZmlsZT0iL2V0Yy9yc3lzbG9nLmQvKi5jb25mIiBtb2RlPSJvcHRpb25hbCIpCgoKICAgICAgICAjIExvZyBjcm9uIHN0dWZmCmNyb24uKiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgL3Zhci9sb2cvY3JvbgoKIyBFdmVyeWJvZHkgZ2V0cyBlbWVyZ2VuY3kgbWVzc2FnZXMKKi5lbWVyZyAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA6b211c3Jtc2c6KgoKIyBTYXZlIG5ld3MgZXJyb3JzIG9mIGxldmVsIGNyaXQgYW5kIGhpZ2hlciBpbiBhIHNwZWNpYWwgZmlsZS4KdXVjcCxuZXdzLmNyaXQgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAvdmFyL2xvZy9zcG9vbGVyCgojIFNhdmUgYm9vdCBtZXNzYWdlcyBhbHNvIHRvIGJvb3QubG9nCmxvY2FsNy4qICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgL3Zhci9sb2cvYm9vdC5sb2ciID4gL2V0Yy9yc3lzbG9nLmNvbmYKbG9jYWw1LiogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAvdmFyL2xvZy9PQ0kvZGVwbG95bWVudC5sb2ciID4gL2V0Yy9yc3lzbG9nLmNvbmYKCgogLSBzeXN0ZW1jdGwgZW5hYmxlIC0tbm93IHJzeXNsb2cKLSBlY2hvICJoZXkgbWF0dCB0aGlzIHdvcmtlZCEiID4gL2hvbWUvb3BjL2l0d29ya2VkLnR4dA=="
		"ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDO0PX2sa490+ikLqLnQGFx+utpD1ih7DWB3vxR6mBYHfL9exgwvWc8+dDUkZQCjUhcOGloPtOA6/UQGXh9aAKjywteJsFIYV+bhfda/yQajra28TeUV/vPqUzBVEuNzAxF4SHmrbsktfk7I4SP9CjejjBWrnSW1UWq/DsbkdIsrUtMblaB+T4bISEOGBwemqvaxUG+AtjUUAa4wCDSr+wX3BE8cY1QNA6CjB8BziYsAibPAhXh9a3/5CLqye0+trjKS7AYg2nNAV9FJUDsIazhWDb9OqZ2f3p7F0yjZOggAgYxOxuvTqDY15WRt5JA0OeecsXUAnpbkCNp1PD/FZAC6gwtRcdrOgTgzrUQKmj8ObVKl2SBJUK+VD2CGifTygv7zBj2GNmwj/XTXFm9+W989KQ/TLKiSPElKMbIuHcnozJBIYJKSuGcokqNUcON9Bmi75JjF90G6q4YZOdSeDQI+kldiWdDp/wbpP4Q5L+A8YNhcdv8P7WeXCXIK5bms4U= mhopper@oci-client.attlocal.net"
	}
	shape = "VM.Standard.E2.1.Micro"
	source_details {
		source_id = "ocid1.image.oc1.iad.aaaaaaaadmdb3soyixuxu5e2btrioamdkqhnnwodcwd67x7c3s2mfnpd3qnq"
		source_type = "image"
	}
}
